### ISSUE TITLE
Need to show EVERY possible combination of options

### ISSUE THREAD

**Issue by ralbright-wa** [peterprib/node-red-contrib-array-permutations#14]
Saw this in the Node-Red install area, and it is so close to being perfect. The only thing it is missing is showing every possible combination of permutations if unique is activated.

For example with an array of numbers 1-7, picking a set of 5 unique numbers:

- 1,2,3,4,5
- 5,4,3,2,1
- 3,4,5,2,1
- etc

Are all valid choices, despite them having all having the same digits just in different orders. (Here is a permutation generator I found online that works well, [https://www.dcode.fr/permutations-generator](https://www.dcode.fr/permutations-generator), however I am really wanting to have this all directly integrated into Node-Red. Makes adding things to the permutation so much easier.)

**Comment by peterprib** [comment]
A while since I look at the code.  Will have a look and try to understand what you expect as behavior and what I have produced as behavior for unique.  There is a definite behavior change on setting this flag which by the logic should generate a differential in permutations produced.

**Comment by peterprib** [comment]
It is working as expected, trying to understand your requirement.  Is it that you want uniqueness disregarding order? Raises the other question, do you expect no array position to appear no more than once in any permutation, that is, array 1,2 does not have 1,1 and 2,2 in answer set.

**Comment by ralbright-wa** [comment]
The problem is when I feed 4 digits and ask for every possible permutation with a set of 4, unique, I get one result. When I feed the same 4 digits into [https://www.dcode.fr/permutations-generator](https://www.dcode.fr/permutations-generator), I get 24 results.
1,2,3,4
2,1,3,4
3,1,2,4
1,3,2,4
2,3,1,4
3,2,1,4
3,2,4,1
2,3,4,1
4,3,2,1
3,4,2,1
2,4,3,1
4,2,3,1
4,1,3,2
1,4,3,2
3,4,1,2
4,3,1,2
1,3,4,2
3,1,4,2
2,1,4,3
1,2,4,3
4,2,1,3
2,4,1,3
1,4,2,3
4,1,2,3
#N : 24

**Comment by peterprib** [comment]
Note that it doesn't produce one message with all permutations but will add.  Have sighted a flaw in individual messages which I will fix. I notice odd behaviour with loop. It appears to work but debug node doesn't appear to display payload.  Have combinations working with same strange issue on debug.

**Comment by ralbright-wa** [comment]
Do you have a coding example to export that type of array set?

**Comment by peterprib** [comment]
have fixed problems and added a few more ways of permunating
